server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5 # 最小空闲时间
      idle-timeout: 600000 # 空闲连接存活最大时间，默认是 60 00 00 ，也就是 10 分钟
      maximum-pool-size: 10 #连接池最大连接数 默认是 10
      auto-commit: true # 自动提交
      max-lifetime: 1800000 # 连接池连接的最大生命周期
      connection-timeout: 30000 # 连接查实的时间 默认 30 秒
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
    show-sql: true
    database: mysql
    properties:
      hibernate:
        #打印执行时间统计信息
#        generate_statistics: true
        jdbc:
          #每批500条提交
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
